### ISSUE TITLE
openbox logout to TDM

### ISSUE THREAD

**Issue by mrneilypops** [dopsi/console-tdm#10]
Hi,
When I log out of openbox I would like to be returned to the TDM console login screen on TTY1 instead of just  
TTY1 and I have to type startx to log back in...
I can achieve this by switching to a different TTY but how can I set this as default?

**Comment by sebastiencs** [comment]
` 2. You must then edit your .profile (or .bash_profile, .zprofile, etc...) file to call tdm as last command (this will launch tdm once you log into a tty). `

At this step, make a loop on tdm. I didn't try it but it should work
