### ISSUE TITLE
`${CONFDIR}/extra` missing after `tdmctl init`

### ISSUE THREAD

**Issue by DuncanvR** [dopsi/console-tdm#14]
After installing the [console-tdm-git](https://aur.archlinux.org/packages/console-tdm-git/) package on Arch, the `extra` folder is missing from `/usr/share/tdm/` on my machine. Invoking `tdmctl init` simply copies everything in `/usr/share/tdm/` to `$/.tdm/`, so there the `extra` folder was missing as well. Consequently calling `tdmctl list` returned an error about the missing folder. Creating the folder myself (`mkdir $/.tdm/extra`) resolved this.

This could very well be considered an issue with the AUR package definitions, since the `Makefile` does create the `extra` folder. It's probably left out of the packages because it's empty. I believe @dopsi is the maintainer for both packages, so I'm sure reporting this here will get his attention.

I see at least three options:
 * Fixing the package definitions to include the empty folder;
 * Adding an empty file to the folder would resolve this (something like `touch $(DESTDIR)$(PREFIX)/share/tdm/extra/.empty` on line 32 of `Makefile`);
 * Extending the `init()` method of `tdmctl` to ensure the `extra` folder is created.

Any thoughts?

**Comment by dopsi** [comment]
Thanks for the info, it is indeed `makepkg` that remove any empty directories from the package before compressing it.

Since I cannot change the behaviour of `makepkg` and don't like the idea of empty files lying around in the file hierarchy, I have modified the behaviour of the `tdmctl init` command.
