### ISSUE TITLE
With `/usr/bin/tdm` in `~/.profile`, after I log in an X session on tty1, I can't log in on tty2.

### ISSUE THREAD

**Issue by crocket** [dopsi/console-tdm#18]
I have `~/.tdm/extra/shell` for the usual console login.
But, I can't log in a console session on tty2 after logging in an X session on tty1 because `tdm` refuses to proceed.

`[[ $(ls -1 /tmp/.X11-unix | wc -l) -gt 0 ]] && fallback 'X started.'` is the culprit.

I just confirmed that I can launch multiple X servers on different `DISPLAY`s. Perhaps, it's time to allow multiple X sessions.

**Comment by crocket** [comment]
It seems that killing only a specific `DISPLAY` is difficult.

It's good to be able to log in extra login sessions when an X session is running.

**Comment by crocket** [comment]
I commented that line out, and I am ok.

Is there any problem with removing it?

**Comment by dopsi** [comment]
@crocket I think it is best to use an option to allow it, since most users will not want to start multiple X sessions. I will add a `--disable-xrunning-check` option to `tdm` in order to disable this check.
