### ISSUE TITLE
The "X running check" feature disables non-X sessions

### ISSUE THREAD

**Issue by fofoni** [dopsi/console-tdm#26]
If I have `tdm` in my `.bash_profile`, and I start X in tty1, and then try to log in tty2, I get immediately dropped to a shell because TDM decided that X was already running. I'd like, however, to have the option of choosing one of the `extra/` sessions using TDM.

Right now, I'm working around this by using `tdm --disable-xrunning-check` in my `.bash_profile`, but I don't believe this was the original purpose of this option.

The most sane solution I can think of would be to have TDM detect a running X session and then display only the `extra/` options to the user (hiding the other, X-related, options). And, of course, it should not hide anything if the `--disable-xrunning-check` option is present. I know that this would take some time to implement, and I'm willing to submit a PR, but I wanted first to make sure that what I just described is the intended behavior.

Thank you for the awesome work by the way; I've been using tdm for some years now, and I love it!

**Comment by dopsi** [comment]
Thanks for the feedback!

> The most sane solution I can think of would be to have TDM detect a running X session and then display only the extra/ options to the user (hiding the other, X-related, options). And, of course, it should not hide anything if the --disable-xrunning-check option is present. I know that this would take some time to implement, and I'm willing to submit a PR, but I wanted first to make sure that what I just described is the intended behavior.

This indeed seems like the best solution and I will gladly accept a PR that implements this more correct behavior (the current one stems from the time `tdm` was merely a `startx` wrapper, in which case it made sense).
