### ISSUE TITLE
[PATCH] Makefile: Support DESTDIR

### ISSUE THREAD

**Issue by hartwork** [dopsi/console-tdm#3]
Hi!

I had to patch `DESTDIR` support in for a semi-official Gentoo ebuild.
Please consider `git-am`'ing [this patch](https://cgit.gentoo.org/proj/betagarden.git/tree/x11-apps/console-tdm/files/console-tdm-1.1.1-destdir.patch?id=39cb2057116ddeb50010ab75266c4ef3eae5a7b6):

Thanks and best, Sebastian

**Comment by dopsi** [comment]
Applied in be812f9. I will release 1.1.2 as soon as #4 is solved.

**Comment by hartwork** [comment]
Cool, thank you!
