### ISSUE TITLE
How do I use the dialog mode at login/session choice time?

### ISSUE THREAD

**Issue by Lakshamana** [dopsi/console-tdm#31]
Issue title explains by its own :)
How can I achieve this? Thanks!

**Comment by dopsi** [comment]
TDM should automatically switch to the dialog mode if `dialog` is installed (if `type dialog` returns something such as `dialog is /usr/bin/dialog`), otherwise it will use the text mode

**Comment by Lakshamana** [comment]
Thanks, @dopsi
