### ISSUE TITLE
how to get selected session's info

### ISSUE THREAD

**Issue by aRmanNM** [dopsi/console-tdm#35]
app is working great. thank u. the problem is i am switching between gnome and openbox sessions. for openbox session i need to set gtk3-nocsd environment variables but not for the other one. so how can i get the selected session's info (at least name) to write my conditional statements? (or maybe a better way to do this)

**Comment by dopsi** [comment]
Currently, there is no formal way to get the selected session info.

However, during the execution of the `tdmexit` script, the `/tmp/tdmdefault` symlink (or `${CONFDIR}/default` if the first one did not exist) points the session which will be executed.

I hope this helps

**Comment by aRmanNM** [comment]
thanks for the response. i actually needed to fix this real quick so i wrote something fast and dirty. i couldn't find `/tmp/tdmdefault` but there was another file in that location named like `tdm_1234` (the number part changed each time i logged in). i dont know if u meant that one but the index of selected session saved in there each time and i could take that using `currentSession=$(cat /tmp/tdm*)`
