### ISSUE TITLE
Tutorial on installing auto-activation

### ISSUE THREAD

**Issue by hartwork** [dopsi/console-tdm#4]
Hi!

I know that for XDM I would install the package and configure the init system to make it run XDM's initscript during the boot process. I am unsure how to achieve more or less the same results with console-tdm. Are there any docs I am missing out?

Thanks and best, Sebastian

**Comment by dopsi** [comment]
I have never used XDM, so I'm not really sure what you mean by auto-activation.

If you want to start console-tdm after login in, you can follow the documentation on the [ArchWiki](https://wiki.archlinux.org/index.php/Console_TDM) (I will add it in the README).

If I did not answer your question, let me know

Simon

**Comment by hartwork** [comment]
Hi!

by auto-activiation I mean that once you passed bootloader and initramfs the first thing to ask for credentials is the display manager, and it's asking for the credentials of the unpriviliged user you want to use the session with.

I have actually read that Arch wiki page before. with my prirt background from a graphical display managers that page is still rather puzzling to me, e.g. `~/.bash_profile` is used without saying which user, when to use that and when to use `~/.xinitrc` instead, who is interpreting the latter, etc. The article only helps if you actually know everything already in a way, which is suboptimal... at least to me :)

Best, Sebastian

**Comment by dopsi** [comment]
I updated the README to include the required steps to get a working setup. Let me know if you have any questions.

**Comment by hartwork** [comment]
Hi!

I finally gave the docs a closer look. So I have a few comments now:

* "It has a helper script, called tdmctl to manage sessions."
  Maybe change this to "[tdm] sessions" to not be confused with X sessions at that point.
* "is start in the shell"
  Typo "start[ed]"
* "If the path is not an executable file, the session is always counted as inactive."
  How did we get from sessions to paths and executables?  Is there a bridge sentence missing?
* "In your .xinitrc file, you must then replace the exec line with tdm --xstart, which will start your X session."
  I didn't have that file at all, so I could not replace anything. Maybe spell out `exec tdm --xstart` here
* My bash ignored `.profile` so I needed to use `.bash_profile` instead.  Maybe mention `.bash_profile` in the docs as well, maybe upfront (due to the order in `man bash`).
* It took me a while to figure that `.profile` and `.xinitrc` are both needed.
  Maybe migrate "Usage" to 1. .... 2. .... 3. ....

Best, Sebastian
